version: '3.8'

services:
  openfga:
    image: openfga/openfga:latest
    container_name: pollen_openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=memory
      - OPENFGA_LOG_FORMAT=text
    ports:
      - "8080:8080" # HTTP API
      - "8081:8081" # gRPC API
      - "3000:3000" # Playground
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:8081"]
      interval: 5s
      timeout: 5s
      retries: 5
