apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pollen-dek-ebpfd
  namespace: kube-system
  labels:
    app: pollen-dek-ebpfd
spec:
  selector:
    matchLabels:
      app: pollen-dek-ebpfd
  template:
    metadata:
      labels:
        app: pollen-dek-ebpfd
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: dek-ebpfd
          image: pollen/dek-ebpfd:v0.1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
                - BPF
          volumeMounts:
            - name: sys-fs-bpf
              mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
            - name: sys-fs-cgroup
              mountPath: /sys/fs/cgroup
          env:
            - name: CGROUP_PATH
              value: "/sys/fs/cgroup/pollen-dek-supervised"
      volumes:
        - name: sys-fs-bpf
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
        - name: sys-fs-cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
