name: Docs Validation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - '*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            docs/**/*.md
            *.md
