name: Packaging Pipeline

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-linux-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-deb
      - run: cargo build --release --workspace --exclude dek-ebpf-prog --exclude dek-ebpfd
      - run: cargo deb -p dek-core
      - uses: actions/upload-artifact@v4
        with:
          name: pollen-dek-linux-deb
          path: target/debian/*.deb

  build-windows-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-wix
      - run: cargo build --release --workspace --exclude dek-ebpf-prog --exclude dek-ebpfd
      - run: cargo wix --no-build -p dek-core
      - uses: actions/upload-artifact@v4
        with:
          name: pollen-dek-windows-msi
          path: target/wix/*.msi
